# Generated by Django 4.1.2 on 2023-06-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_recipe_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('cooking_time', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.ImageField(blank=True, default='media/images/default.jpg', null=True, upload_to='images/')),
            ],
        ),
    ]
