# Generated by Django 4.1.2 on 2023-06-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_userrecipe_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecipe',
            name='image_url',
            field=models.ImageField(blank=True, default='media/images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
